<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
<script>
  /**
   * 登录
   * resolve 表示获取结果成功, reject 表示失败
   * 无论 resolve 还是 reject 都会将括号中的结果抛出, resolve 的结果会进入 then 中, reject 的结果会进入 catch 中
   * @param resolve 成功
   * @param reject 失败
   */
  function login(resolve, reject) {
    setTimeout(() => {
      // 生成随机数模拟登录成功或失败
      let num = Math.random()
      if (num > 0.5) {
        resolve("login success")
      }else {
        reject("login failed")
      }
    }, 1000)
  }

  new Promise(login).then(data => {
    //如果 login 将来执行成功（就是 resolve 方法抛出执行结果的时候）
    console.log("then1:", data);
    return data;
  }).then(data=>{
    console.log("then2:", data);
    return data;
  }).then(data=>{
    // throw new Error("出错啦");
  }).catch(err=>{
    console.error("err1:", err);
  }).finally(()=>{
    console.log("over!")
  }).then(()=>{
    console.log("========")
  })
</script>
</body>
</html>
